from .animal_requests import get_all_animals, get_single_animal, create_animal, delete_animal, update_animal, get_animal_by_location, get_animal_by_status
from .location_requests import get_all_locations, get_single_location
from .customer_requests import get_all_customers, get_single_customer, get_customers_by_email, get_customers_by_name
from .employee_requests import get_all_employees, get_single_employee, get_employee_by_location